/*
 * term_ops.cpp
 *
 *  Created on: Nov 21, 2014
 *      Author: dejan
 */

#include "expr/term_ops.h"

#include <iostream>

namespace sal2 {
namespace expr {

std::ostream& operator << (std::ostream& out, term_op op) {

#define SWITCH_TO_STRING(op) case op: out << #op; break;
  switch (op) {
    SWITCH_TO_STRING(TYPE_BOOL)
    SWITCH_TO_STRING(TYPE_INTEGER)
    SWITCH_TO_STRING(TYPE_REAL)
    SWITCH_TO_STRING(TYPE_STRUCT)
    SWITCH_TO_STRING(VARIABLE)
    SWITCH_TO_STRING(TERM_EQ)
    SWITCH_TO_STRING(TERM_ITE)
    SWITCH_TO_STRING(CONST_BOOL)
    SWITCH_TO_STRING(TERM_AND)
    SWITCH_TO_STRING(TERM_OR)
    SWITCH_TO_STRING(TERM_NOT)
    SWITCH_TO_STRING(TERM_IMPLIES)
    SWITCH_TO_STRING(TERM_XOR)
    SWITCH_TO_STRING(CONST_RATIONAL)
    SWITCH_TO_STRING(TERM_ADD)
    SWITCH_TO_STRING(TERM_SUB)
    SWITCH_TO_STRING(TERM_MUL)
    SWITCH_TO_STRING(TERM_DIV)
    SWITCH_TO_STRING(TERM_LEQ)
    SWITCH_TO_STRING(TERM_LT)
    SWITCH_TO_STRING(TERM_GEQ)
    SWITCH_TO_STRING(TERM_GT)
    SWITCH_TO_STRING(CONST_STRING)
    SWITCH_TO_STRING(OP_LAST)
    SWITCH_TO_STRING(CONST_BITVECTOR)
    SWITCH_TO_STRING(TERM_BV_ADD)
    SWITCH_TO_STRING(TERM_BV_SUB)
    SWITCH_TO_STRING(TERM_BV_MUL)
    SWITCH_TO_STRING(TERM_BV_DIV)
    SWITCH_TO_STRING(TERM_BV_UDIV)
    SWITCH_TO_STRING(TERM_BV_SDIV)
    SWITCH_TO_STRING(TERM_BV_UREM)
    SWITCH_TO_STRING(TERM_BV_SREM)
    SWITCH_TO_STRING(TERM_BV_SMOD)
    SWITCH_TO_STRING(TERM_BV_XOR)
    SWITCH_TO_STRING(TERM_BV_SHL)
    SWITCH_TO_STRING(TERM_BV_LSHR)
    SWITCH_TO_STRING(TERM_BV_ASHR)
    SWITCH_TO_STRING(TERM_BV_NOT)
    SWITCH_TO_STRING(TERM_BV_AND)
    SWITCH_TO_STRING(TERM_BV_OR)
    SWITCH_TO_STRING(TERM_BV_NAND)
    SWITCH_TO_STRING(TERM_BV_NOR)
    SWITCH_TO_STRING(TERM_BV_XNOR)
    SWITCH_TO_STRING(TERM_BV_CONCAT)
    SWITCH_TO_STRING(TERM_BV_EXTRACT)
    SWITCH_TO_STRING(TERM_BV_ULEQ)
    SWITCH_TO_STRING(TERM_BV_SLEQ)
    SWITCH_TO_STRING(TERM_BV_ULT)
    SWITCH_TO_STRING(TERM_BV_SLT)
    SWITCH_TO_STRING(TERM_BV_UGEQ)
    SWITCH_TO_STRING(TERM_BV_SGEQ)
    SWITCH_TO_STRING(TERM_BV_UGT)
    SWITCH_TO_STRING(TERM_BV_SGT)

  default:
    out << "unknown";
  }
#undef SWITCH_TO_STRING
  return out;
}

}
}
