#!/bin/bash 

INPUT=$1
PROPERTY=$2

$HOME/Software/sal-3.3/bin/salenv-safe <<EOF
(sal/set-pp-max-width! 10000)
(sal/set-pp-max-depth! 10000)
(sal/set-pp-max-num-lines! 100000)
(sal/set-sal-pp-proc! sal-ast->lsal-doc) 
(make-flat-assertion "$INPUT!$PROPERTY")
EOF

